### ISSUE TITLE
Firmware fails to start on WSL

### ISSUE THREAD

**Issue by TBM13** [kimocoder/realtek_wifi#35]
I'm trying to use this driver on WSL.
Device (TP-LINK TL-WN722N v2 with RTL8188EU) is detected and firmware loads, but fails to start.
Here's the log:
[dmesg.txt](https://github.com/kimocoder/realtek_rtwifi/files/10826108/dmesg.txt)

Device works fine on WSL with aircrack's rtl8188eus driver.

Here's the kernel I'm using:
https://github.com/TBM13/WSL2-Linux-Kernel
Since its version is 5.15, I had to modify this driver to compile:
https://github.com/TBM13/realtek_rtwifi

**Comment by TBM13** [comment]
[Bypassing the check](https://github.com/TBM13/realtek_rtwifi/commit/bc2b34e25b38990f4957add37f7e695c35c15faf) makes everything work fine, so the issue is probably in detecting whether the firmware started or not. You can close this is if you want

**Comment by TBM13** [comment]
Another issue I have is that monitor mode stops capturing anything after running hcxdumptool once or doing things like switching to managed and then monitor mode again, downing and upping the interface, etc. Once this happens, I have to disconnect the adapter from WSL and reconnect it.
This may be what [ZerBea mentioned](https://github.com/kimocoder/realtek_rtwifi/issues/34#issuecomment-1385027035), I'm not sure.

**Comment by ZerBea** [comment]
Removed this comment, because drive is fixed, now.

**Comment by dubhater** [comment]
@TBM13 What if instead of bypassing the check completely you double RTL8XXXU_FIRMWARE_POLL_MAX? It's defined in rtl8xxxu.h.

**Comment by TBM13** [comment]
> @TBM13 What if instead of bypassing the check completely you double RTL8XXXU_FIRMWARE_POLL_MAX? It's defined in rtl8xxxu.h.

Yes, I have already tried that but it didn't work. I tried setting it to 5000 and 10000

**Comment by ZerBea** [comment]
There is a new firmware v.28 available:
https://bugzilla.kernel.org/show_bug.cgi?id=217205#c45

**Comment by TBM13** [comment]
> There is a new firmware v.28 available: https://bugzilla.kernel.org/show_bug.cgi?id=217205#c45

  No luck, the issue still persists.
As additional information, I upgraded to [Linux 6.1](https://github.com/TBM13/WSL2-Linux-Kernel/tree/linux-msft-wsl-6.1.y), so I'm now using this driver pretty much unaltered (except for [this single commit](https://github.com/TBM13/realtek_rtwifi/commit/877c35d4a45a34c25bc3c2d0fcbe4dd94c82dd1d))

**Comment by TBM13** [comment]
After doing some quick testing, driver stability seems to have improbed a lot. I don't know if that's because I updated the kernel, the firmware or fetched the latest commits of this repo, but I can finally switch between monitor and managed mode multiple times without making the card not detect networks anymore

**Comment by kimocoder** [comment]
Wake TX Queue is included related  to several drivers from 6.1+ and caused issues earlier and was disabled for long time.
